feat: add getTransactionId method
Adamant-im/adamant-api-jsclient pull request #36
Opened 2023-10-27 16:00 UTC by martiliones

Usage:

```js
import {getTransactionId} from 'adamant-api'
const id = getTransactionId(signedTransaction)
```

2023-10-30 22:41 UTC, adamant-al commented
@martiliones 
Does the node returns the same tx id?
Post an example here—first, create a tx locally and get its tx id, then broadcast to an ADAMANT node and get the results.

2023-10-31 10:01 UTC, martiliones commented
>  Does the node return the same tx id?

yes, I have tested it with message transaction as you can see in `examples/` directory

> Post an example here—first, create a tx locally and get its tx id, then broadcast to an ADAMANT node and get the results.

I added tests now where transaction objects were taken from msg.adamant.im requests body. Tests include URLs to ahead node api to check transactions ID out:
```js
// https://ahead.adamant.im/api/transactions/get?id=10707920525275969664&returnAsset=1
expect(id).toBe('10707920525275969664');
```

2023-10-31 10:47 UTC, adamant-al approved these changes

2023-10-31 22:20 UTC, bludnic requested changes

2023-10-31 22:20 UTC, bludnic commented on examples/getId/index.ts
> +import {getTransactionId} from '../../dist';
```suggestion
import {getTransactionId} from 'adamant-api';
```

2023-10-31 22:20 UTC, bludnic approved these changes

2023-10-31 22:24 UTC, merged