Fix/transaction query
Adamant-im/adamant-api-jsclient pull request #51
Opened 2024-01-26 04:02 UTC by martiliones

### Fixed

transforms object from:
```js
const blocks = await api.getTransactions({
  fromHeight: 7585271,
  and: {
    toHeight: 7586280,
  },
  or: {
    senderId: 'U18132012621449491414',
  }
});
```

to 

```html
fromHeight=7585271&and:toHeight=7586280&or:senderId=U18132012621449491414
```

### Added

- Export `transformTransactionQuery` function

2024-01-26 17:34 UTC, bludnic requested changes

2024-01-26 17:34 UTC, bludnic commented on src/api/index.ts
> +export type TransactionQuery<T extends {}> = Partial<T> & {
Isn't `T extends Record<string, never>` more suitable?

Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- **If you want a type meaning "empty object", you probably want `Record<string, never>` instead.**
- If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead.

2024-02-29 11:05 UTC, adamant-al commented
@martiliones 

Check it.

2024-03-01 18:23 UTC, bludnic approved these changes

2024-03-01 18:23 UTC, bludnic commented on src/api/index.ts
> +export type TransactionQuery<T extends object> = Partial<T> & {
Why you use `object` instead of `Record<string, never>`?

2024-03-02 14:23 UTC, martiliones commented on src/api/index.ts
> +export type TransactionQuery<T extends object> = Partial<T> & {
because we need an object with existing properties

2024-03-02 14:32 UTC, merged