Fix/vote for delegate
Adamant-im/adamant-api-jsclient pull request #57
Opened 2024-04-23 20:57 UTC by martiliones

### `api.voteForDelegate()`

- fix: validation for public keys and delegate names
- chore: better logging
- chore: updated example

2024-04-24 07:43 UTC, adamant-al commented on src/api/index.ts
> +          console.log('couldnt get delegates publickey');
Forgot to clean up?

2024-04-24 14:01 UTC, bludnic commented on src/api/index.ts
> +            "couldn't get address' public key"
Is this a typo `address'`?

2024-04-24 14:53 UTC, bludnic commented
```js
const result = await api.voteForDelegate('passphrase...', [
  '+U123456'
])
```

**Actual:**

Votes is `+null`

![Screenshot 2024-04-24 3 52 34 PM](https://github.com/Adamant-im/adamant-api-jsclient/assets/25831507/451029b9-d833-4b51-a4da-84a2909d242e)

**Expected:**

Rejected if error if no public key

2024-04-24 14:55 UTC, bludnic commented
Can you add a validation to check that the user is actually a Delegate? @martiliones 
Voting for a regular user may result in a waste of ADM tokens.

2024-04-24 15:04 UTC, bludnic requested changes

2024-04-24 15:04 UTC, bludnic commented on src/api/index.ts
>    async voteForDelegate(passphrase: string, votes: string[]) {
Add `@param passphrase Account's passphrase` to JSDoc.

2024-04-24 15:04 UTC, bludnic commented on src/api/index.ts
> +          "the vote doesn't look like public key, address or delegate name"
```js
const result = await api.voteForDelegate('passphrase...', [
  'U123456'
])
```

Result:

```js
{
  success: false,
  error: "Wrong 'votes' parameter: 123456. Error: the vote doesn't look like public key, address or delegate namethe vote doesn't look like public key, address or delegate name"
}
```

The message is logged two times.

![Screenshot 2024-04-24 3 44 24 PM](https://github.com/Adamant-im/adamant-api-jsclient/assets/25831507/271aecab-1680-46aa-87e2-f554c5477ca3)

2024-04-24 18:19 UTC, adamant-al commented
> Can you add a validation to check that the user is actually a Delegate? @martiliones Voting for a regular user may result in a waste of ADM tokens.

Do we want one more request?

2024-04-24 20:30 UTC, martiliones commented
> Do we want one more request?

Well, it can be done using the single request by retrieving all the delegates, since the amount of them is limited to 101, then find the delegate by address there. It doesn't cost much performance for a node since it does exactly the same under the hood for `/delegates/get`

It would be nice if we had `/delegates/get` endpoint optimized for finding a single delegate with addition of `address` parameter

2024-04-25 05:40 UTC, adamant-al commented
> It would be nice if we had `/delegates/get` endpoint optimized for finding a single delegate with addition of `address` parameter

You can create a Trello task for this and refer to the comment.

2024-05-28 22:08 UTC, bludnic approved these changes

2024-05-30 06:02 UTC, merged