feat: add connection events and subscription to multiple addresses, t…
Adamant-im/adamant-api-jsclient pull request #67
Opened 2024-12-15 20:11 UTC by yoxira

simple test script:

```js
const nodes = [
  'https://endless.adamant.im',
  'https://clown.adamant.im',
  'http://23.226.231.225:36666',
  'http://88.198.156.44:36666',
  'https://lake.adamant.im',
];

const admAddresses = ['U8084717991279447871'];

const socket = new WebSocketClient({admAddresses});

socket.onConnection(node => {
  console.log(`We connected to ${node}...`);
  console.log('...to disconnect from it');

  // disconnect to test reconnection
  socket.connection.disconnect();

  // // Uncomment to block following reconnections:
  // socket.nodes = [{wsType: 'ws', ip: '127.0.0.1'}];
});

socket.catch(err => {
  if (err.name === 'AdamantWsError') {
    if (err.reason === 'connection_error' || err.reason === 'disconnection') {
      console.log('We gave up on reconnecting!');
    }
  }
});

// We can use socket.reviseConnection(nodes) instead but then we need manually check the nodes
new AdamantApi({
  nodes,
  socket,
});
```

2024-12-15 21:26 UTC, yoxira commented
Updated documentation:
> **WebSocket Connections**
> https://github.com/Adamant-im/adamant-api-jsclient/wiki/WebSocket-Connections

2024-12-19 00:09 UTC, bludnic commented on src/helpers/wsClient/wsClient.ts
>    constructor(options: WsOptions) {
Trying to subscribe to any transaction without using specific ADM address. The handler is not triggered at all. @yoxira 

```js
import {AdamantApi, WebSocketClient} from '../../dist';

const nodes = ['https://ahead.adamant.im'];
const socket = new WebSocketClient({});

socket.on(transaction => {
  console.log('New transaction:', transaction.id, transaction.type);
});

const api = new AdamantApi({
  nodes,
  socket,
});
```

2024-12-19 00:10 UTC, bludnic commented on src/helpers/wsClient/wsClient.ts
>    constructor(options: WsOptions) {
Logs:

![image](https://github.com/user-attachments/assets/b9bf93a6-d34e-415a-bda9-5ffb51b67758)

2024-12-23 05:13 UTC, bludnic commented
After `pnpm install` the `pnpm-lock.yaml` changed. 

![image](https://github.com/user-attachments/assets/2333f3df-4438-446c-b17d-ff2db424fc86)

Can you upgrade to the latest version and commit the `pnpm-lock.yaml`? @yoxira 

![image](https://github.com/user-attachments/assets/683d76db-e2b2-4aee-93ef-8367e93bd102)

2024-12-23 05:29 UTC, bludnic requested changes

2024-12-23 05:29 UTC, bludnic commented on src/helpers/wsClient/wsClient.ts
> +}
Do you need that type? Currently not used anywhere.

2024-12-23 05:29 UTC, bludnic commented on src/helpers/wsClient/wsClient.ts
> +  private reconnect(reconnectReason: ReconnectReason) {
Can you add a method to close the Socket connection externally? @yoxira

2025-01-04 14:46 UTC, adamant-al commented
@bludnic 
Review

@yoxira 
What's min ADM node version works with this?
If it's higher than 0.8.3, we better filter nodes in health check?

2025-01-08 18:49 UTC, bludnic commented
Firstly, we can prioritize WS connections for nodes with higher versions.

In the case a node with old version (`<0.8.4`) is chosen for WS subscription:

1. If multiple ADM addresses are provided for subscription (`options.admAddresses`), only the first one will be selected, and a warning will be emitted:
*The [NODE:PORT] does not support subscription for multiple addresses. Only the U123456 address will be watched.*

2. Other options, such as filtering by `options.types` and `options.assetChatTypes` will be ignored. A warning should also be shown, indicating that these options have no effect.

2025-01-08 20:41 UTC, adamant-al commented
> Firstly, we can prioritize WS connections for nodes with higher versions.
> 
> In the case a node with old version (`<0.8.4`) is chosen for WS subscription:
> 
> 1. If multiple ADM addresses are provided for subscription (`options.admAddresses`), only the first one will be selected, and a warning will be emitted:
>    _The [NODE:PORT] does not support subscription for multiple addresses. Only the U123456 address will be watched._
> 2. Other options, such as filtering by `options.types` and `options.assetChatTypes` will be ignored. A warning should also be shown, indicating that these options have no effect.

I suppose ignore nodes with old version (`<0.8.4`).
Soon users update most nodes, and we'll not support legacy.

2025-01-08 21:18 UTC, bludnic commented
@adamant-al I agree. Let's do as you suggested.

2026-06-21 12:18 UTC, dev-adamant-im commented
Thank you for the original implementation and review work. This PR has been superseded by the rewritten and tested WebSocket implementation merged into `dev` through #81 (merge commit `4bd8cd2`) and included in release PR #84.

The current implementation covers the scope of this PR:

- subscriptions by multiple `admAddresses`, transaction `types`, and `assetChatTypes`;
- `connect()` and `disconnect()` with pending-reconnect cancellation and listener cleanup;
- bounded reconnection through `maxTries` and `reconnectionDelay`;
- `onConnection` and `onReconnection` lifecycle callbacks;
- typed `AdamantWsConnectionError` reporting for connection/disconnection exhaustion;
- health-check minimum-version filtering before API and WebSocket node selection.

It also adds focused tests for subscription payloads, message-type handlers, lifecycle callbacks, manual disconnect, reconnect cancellation, exhausted attempts, and dead-socket cleanup. The complete `dev` suite passes (19 suites, 214 tests).

The old branch is no longer suitable for merging because its lockfile and source layout predate the v3 modularization. Closing as superseded by #81.

2026-06-21 12:18 UTC, closed without merging